[tool.poetry]
name = "secret-santa-py"
version = "0.1.0"
description = "generate secret santa combinations and anonymously send via text message"
authors = ["Ian Davis <ian@aloosefish.com>"]
readme = "README.md"
packages = [{ include = "secret_santa_py" }] # this cause issue?

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
twilio = "^8.4.0"
Faker = "^18.11.1"
pytest = "^7.4.0"
keyring = "^24.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
