[tool.poetry]
name = "secret-santa-py"
version = "1.0.0"
description = "generate secret santa combinations and anonymously send via text message"
authors = ["Ian Davis <ian@aloosefish.com>"]
readme = "README.md"
packages = [{ include = "secret_santa_py" }]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
twilio = "^8.4.0"
Faker = "^18.11.1"
keyring = "^24.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"

[tool.pytest.ini_options]
pythonpath =[
    "."
]
minversion = "7.0"
addopts = [
    "-ra -v"
]

testpaths = "tests"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
