name: Run Secret Santa Script On Schedule

on:
  schedule:
    #    “At 23:05 UTC (6:05pm CST) on day-of-month 11 and on Friday in November.”
    - cron: "5 23 11 11 5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-python@4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run python cloud_run.py ${{ secrets.twilio_account_sid }} ${{ secrets.twilio_auth_token }} ${{ secrets.twilio_phone_number }} ${{ secrets.json_data_url }} ${{ secrets.json_data_key }}