name: Automerge Dependabot PRs

on:
  pull_request:
    types: [opened]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR if checks pass
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
          headers: |
            Authorization: ${{ secrets.GITHUB_TOKEN }}
          body: |
            {
              "commit_title": "Auto-merge Dependabot PR",
              "commit_message": "Automatically merged by GitHub Actions",
              "sha": "${{ github.event.pull_request.head.sha }}",
              "merge_method": "merge"
            }
        if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == null && github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.draft == false && github.event.review.state == 'approved'
