on:
  schedule:
    #    “At 01:50 UTC (9pm CST) on day-of-month 26 in October.”
    - cron: "50 01 26 10 *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Poetry Install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.5.1-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != true

      - run: poetry run python src/cloud_run.py ${{ secrets.TWILIO_ACCOUNT_SID }} ${{ secrets.TWILIO_AUTH_TOKEN }} ${{ secrets.TWILIO_PHONE_NUMBER }} ${{ secrets.JSON_DATA_URL }} ${{ secrets.JSON_DATA_KEY }}
