# basically this: https://jacobian.org/til/github-actions-poetry/

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.14"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Define a custom uv cache path
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-local-path: "~/.local/cache"

      - name: Run tests
        run: uv run pytest tests --cov src --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

